# Generated by Django 5.2 on 2025-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0003_alerta_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('categoria', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('deviceid', models.CharField(max_length=100)),
            ],
        ),
    ]
