# Generated by Django 5.2.3 on 2025-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0006_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='estado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
